#this file is autogenerated no write manually
def getcss(): return """/*style css ----------------------------------------*/
body {
  background-color: darkblue;
  font-family: Arial, Helvetica, sans-serif;
  font-size:  3.1ex;
}
#container {
  background-color: whitesmoke;
  border-radius: 20px;
  padding: 20px;
  margin: 20px;
}
/*Nagigation header -------------------------------- */
#navigation {
  color: black;
  font-weight: bold;
  text-decoration: none;
  overflow-wrap: break-word;
  word-wrap: break-word;
}
#navigation :visited {
  color: black;
}
#navigation a { 
  text-decoration: none;
}
#navigatio a:hover{
  color: red;
}
/*--------------------------------------------------- */
"""
def getjs(): return """/*script javascript*/
console.log("hello world")
"""